// <auto-generated />
using ITIFinalProject.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITIFinalProject.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20240910045925_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITIFinalProject.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Devices and gadgets",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Apparel and accessories",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Furniture and kitchenware",
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Various genres and authors",
                            Name = "Books"
                        });
                });

            modelBuilder.Entity("ITIFinalProject.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CategoryId = 1,
                            Description = "Latest model with high resolution camera",
                            ImagePath = "smartphone.jpg",
                            Price = 699.99000000000001,
                            Quantity = 50,
                            Title = "Smartphone"
                        },
                        new
                        {
                            Id = 102,
                            CategoryId = 2,
                            Description = "Noise-cancelling over-ear headphones",
                            ImagePath = "bluetooth_headphones.jpg",
                            Price = 89.989999999999995,
                            Quantity = 150,
                            Title = "Bluetooth Headphones"
                        },
                        new
                        {
                            Id = 201,
                            CategoryId = 3,
                            Description = "Stylish leather jacket for winter",
                            ImagePath = "leather_jacket.jpg",
                            Price = 129.99000000000001,
                            Quantity = 30,
                            Title = "Leather Jacket"
                        },
                        new
                        {
                            Id = 202,
                            CategoryId = 4,
                            Description = "Comfortable running shoes with good support",
                            ImagePath = "running_shoes.jpg",
                            Price = 79.989999999999995,
                            Quantity = 100,
                            Title = "Running Shoes"
                        });
                });

            modelBuilder.Entity("ITIFinalProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Password")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "@gamil.com",
                            FirstName = "Omar",
                            LastName = "Ali",
                            Password = 1234
                        },
                        new
                        {
                            Id = 2,
                            Email = "@gamil.com",
                            FirstName = "Mohamed",
                            LastName = "Omar",
                            Password = 8374
                        },
                        new
                        {
                            Id = 3,
                            Email = "@gamil.com",
                            FirstName = "Esraa",
                            LastName = "Ahmed",
                            Password = 9237
                        },
                        new
                        {
                            Id = 4,
                            Email = "@gamil.com",
                            FirstName = "Hoda",
                            LastName = "Abdelrahman",
                            Password = 1754
                        },
                        new
                        {
                            Id = 5,
                            Email = "@gamil.com",
                            FirstName = "Menna",
                            LastName = "Hamza",
                            Password = 9017
                        },
                        new
                        {
                            Id = 6,
                            Email = "@gamil.com",
                            FirstName = "Kareem",
                            LastName = "Bahaa",
                            Password = 8692
                        });
                });

            modelBuilder.Entity("ITIFinalProject.Models.Product", b =>
                {
                    b.HasOne("ITIFinalProject.Models.Category", "category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("ITIFinalProject.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
